export const loginUser = "LOGIN_USER";
export const logoutUser = "LOGOUT_USER";
export const addtocart="ADD_TO_CART";
export const increaseQuantity = 'INCREASE_QUANTITY';
export const decreaseQuantity = 'DECREASE_QUANTITY';
export const removeItem="REMOVE_ITEM";
export const clearCart="CLEAR_ITEM";
export const SiderBarOpen="SIDE_BAR_OPEN";
export const addressData="ADDRESS_DATA";